# 客户结构与预订渠道分析

**分析目标**：
1. 对比不同 hotel 类型的预订量分布
2. 分析不同 customer_type 的预订量与取消行为
3. 剖析 market_segment 和 distribution_channel 的预订量、取消率与平均 ADR
4. 识别主要客源国家 Top 10
5. 探究重复客户（is_repeated_guest）的预订行为特征

> **注意**：`set_plot_style()` 已修复中文字体配置，旧的乱码图片已删除。请 **按顺序重新运行本 Notebook 中所有生成图表的单元格**，以确保新保存的图片中文正常显示。需要重新运行的图表单元格包括：第 2、3、4、5、6、7 步中的绘图 + `save_figure()` 调用。

In [1]:
import sys
import os
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

print(f"项目根目录: {PROJECT_ROOT}")

项目根目录: c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from src.config import PROCESSED_DATA_PATH, FIGURE_DIR
from src.analysis import (
    load_cleaned_data,
    calculate_cancel_rate_by_group,
    calculate_group_summary,
)
from src.visualization import set_plot_style, save_figure

set_plot_style()
os.makedirs(FIGURE_DIR, exist_ok=True)

print("导入完成。")

导入完成。

---
## 第 1 步：读取清洗后数据

In [3]:
df = load_cleaned_data(PROCESSED_DATA_PATH)
print(f"数据集大小: {df.shape[0]:,} 行 x {df.shape[1]} 列")
print(f"酒店类型: {df['hotel'].unique()}")
print(f"客户类型: {df['customer_type'].unique()}")
print(f"市场细分: {df['market_segment'].unique()}")
print(f"分销渠道: {df['distribution_channel'].unique()}")
df.head(3)

数据集大小: 119,390 行 x 42 列
酒店类型: ['Resort Hotel' 'City Hotel']
客户类型: ['Transient' 'Contract' 'Transient-Party' 'Group']
市场细分: ['Direct' 'Corporate' 'Online TA' 'Offline TA/TO' 'Complementary' 'Groups'
 'Undefined' 'Aviation']
分销渠道: ['Direct' 'Corporate' 'TA/TO' 'Undefined' 'GDS']

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,has_agent,arrival_date,total_nights,total_guests,is_family,lead_time_group,adr_level,season,room_match,is_valid_guest
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,2015-07-01,0,2,0,180天以上,异常/免费,夏季,1,0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,2015-07-01,0,2,0,180天以上,异常/免费,夏季,1,0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,2015-07-01,1,1,0,0-7天,低,夏季,0,1

---
## 第 2 步：Hotel 类型预订量对比

In [4]:
hotel_bookings = df["hotel"].value_counts()
hotel_pct = df["hotel"].value_counts(normalize=True)
print("各酒店类型预订量:")
for h in hotel_bookings.index:
    print(f"  {h}: {hotel_bookings[h]:,} 条 ({hotel_pct[h]:.1%})")

各酒店类型预订量:
  City Hotel: 79,330 条 (66.4%)
  Resort Hotel: 40,060 条 (33.6%)

In [5]:
fig, ax = plt.subplots(figsize=(8, 5))
colors = sns.color_palette("Set2", len(hotel_bookings))
bars = ax.bar(hotel_bookings.index, hotel_bookings.values, color=colors)
ax.set_title("各酒店类型预订量对比", fontsize=14, fontweight="bold")
ax.set_xlabel("酒店类型")
ax.set_ylabel("预订量")
for bar, val, pct in zip(bars, hotel_bookings.values, hotel_pct.values):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 500,
            f"{val:,}  ({pct:.1%})", ha="center", fontsize=11)
fig.tight_layout()
save_figure(fig, "03_booking_by_hotel.png")

图表已保存: outputs/figures\03_booking_by_hotel.png

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\2681969051.py:10: UserWarning: Glyph 37202 (\N{CJK UNIFIED IDEOGRAPH-9152}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\2681969051.py:10: UserWarning: Glyph 24215 (\N{CJK UNIFIED IDEOGRAPH-5E97}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\2681969051.py:10: UserWarning: Glyph 31867 (\N{CJK UNIFIED IDEOGRAPH-7C7B}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\2681969051.py:10: UserWarning: Glyph 22411 (\N{CJK UNIFIED IDEOGRAPH-578B}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\2681969051.py:10: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\2681969051.py:10: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\2681969051.py:10: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\2681969051.py:10: UserWarning: Glyph 21508 (\N{CJK UNIFIED IDEOGRAPH-5404}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\2681969051.py:10: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\2681969051.py:10: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from current font.
  fig.tight_layout()
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 37202 (\N{CJK UNIFIED IDEOGRAPH-9152}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 24215 (\N{CJK UNIFIED IDEOGRAPH-5E97}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 31867 (\N{CJK UNIFIED IDEOGRAPH-7C7B}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 22411 (\N{CJK UNIFIED IDEOGRAPH-578B}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 21508 (\N{CJK UNIFIED IDEOGRAPH-5404}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from current font.
  fig.savefig(filepath)

**阶段性结论**：City Hotel 的预订量明显高于 Resort Hotel，城市酒店是业务主体。

---
## 第 3 步：Customer Type 预订量与取消率

In [6]:
cust_stats = calculate_cancel_rate_by_group(df, "customer_type")
cust_stats

,customer_type,total_bookings,canceled_bookings,non_canceled_bookings,cancel_rate
0,Transient,89613,36514,53099,0.407463
1,Contract,4076,1262,2814,0.309617
2,Transient-Party,25124,6389,18735,0.254299
3,Group,577,59,518,0.102253

In [7]:
fig, ax = plt.subplots(figsize=(10, 5))
colors = sns.color_palette("Set2", len(cust_stats))
bars = ax.bar(cust_stats["customer_type"], cust_stats["total_bookings"], color=colors)
ax.set_title("各客户类型预订量与取消率", fontsize=14, fontweight="bold")
ax.set_xlabel("客户类型")
ax.set_ylabel("预订量")
for bar, total, rate in zip(bars, cust_stats["total_bookings"], cust_stats["cancel_rate"]):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 300,
            f"{total:,}  \n取消率: {rate:.1%}", ha="center", fontsize=10)
fig.tight_layout()
save_figure(fig, "03_booking_by_customer_type.png")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 23458 (\N{CJK UNIFIED IDEOGRAPH-5BA2}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 25143 (\N{CJK UNIFIED IDEOGRAPH-6237}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 31867 (\N{CJK UNIFIED IDEOGRAPH-7C7B}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 22411 (\N{CJK UNIFIED IDEOGRAPH-578B}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 21508 (\N{CJK UNIFIED IDEOGRAPH-5404}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 21462 (\N{CJK UNIFIED IDEOGRAPH-53D6}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 28040 (\N{CJK UNIFIED IDEOGRAPH-6D88}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3710873577.py:10: UserWarning: Glyph 29575 (\N{CJK UNIFIED IDEOGRAPH-7387}) missing from current font.
  fig.tight_layout()
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 23458 (\N{CJK UNIFIED IDEOGRAPH-5BA2}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 25143 (\N{CJK UNIFIED IDEOGRAPH-6237}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 31867 (\N{CJK UNIFIED IDEOGRAPH-7C7B}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 22411 (\N{CJK UNIFIED IDEOGRAPH-578B}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 21508 (\N{CJK UNIFIED IDEOGRAPH-5404}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 21462 (\N{CJK UNIFIED IDEOGRAPH-53D6}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 28040 (\N{CJK UNIFIED IDEOGRAPH-6D88}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 29575 (\N{CJK UNIFIED IDEOGRAPH-7387}) missing from current font.
  fig.savefig(filepath)

图表已保存: outputs/figures\03_booking_by_customer_type.png

**阶段性结论**：Transient（散客）是绝对主力客群，但 Transient-Party 的取消率最高，需重点关注。Contract 类型客户的取消率最低，合同客户稳定性强。

---
## 第 4 步：Market Segment 分析（预订量、取消率、ADR）

In [8]:
market_stats = calculate_group_summary(df, "market_segment")
market_stats

  market_segment  total_bookings  canceled_bookings  avg_adr  cancel_rate
0      Online TA           56477              20739   117.20     0.367211
1  Offline TA/TO           24219               8311    87.35     0.343160
2         Groups           19811              12097    79.48     0.610620
3         Direct           12606               1934   115.45     0.153419
4      Corporate            5295                992    69.36     0.187347
5  Complementary             743                 97     2.89     0.130552
6       Aviation             237                 52   100.14     0.219409
7      Undefined               2                  2    15.00     1.000000

In [9]:
fig, ax = plt.subplots(figsize=(10, 5))
data = market_stats.sort_values("total_bookings")
colors = sns.color_palette("Set2", len(data))
bars = ax.barh(data["market_segment"], data["total_bookings"], color=colors)
ax.set_title("各市场细分预订量、取消率与平均 ADR", fontsize=14, fontweight="bold")
ax.set_xlabel("预订量")
ax.set_ylabel("市场细分")
for bar, total, rate, adr in zip(bars, data["total_bookings"],
                                   data["cancel_rate"], data["avg_adr"]):
    ax.text(bar.get_width() + 300, bar.get_y() + bar.get_height() / 2,
            f"{total:,}  |  取消率 {rate:.1%}  |  ADR {adr:.0f}",
            va="center", fontsize=9)
fig.tight_layout()
save_figure(fig, "03_market_segment_analysis.png")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 24066 (\N{CJK UNIFIED IDEOGRAPH-5E02}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 22330 (\N{CJK UNIFIED IDEOGRAPH-573A}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 32454 (\N{CJK UNIFIED IDEOGRAPH-7EC6}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 20998 (\N{CJK UNIFIED IDEOGRAPH-5206}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 21508 (\N{CJK UNIFIED IDEOGRAPH-5404}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 12289 (\N{IDEOGRAPHIC COMMA}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 21462 (\N{CJK UNIFIED IDEOGRAPH-53D6}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 28040 (\N{CJK UNIFIED IDEOGRAPH-6D88}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 29575 (\N{CJK UNIFIED IDEOGRAPH-7387}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 24179 (\N{CJK UNIFIED IDEOGRAPH-5E73}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\586226493.py:13: UserWarning: Glyph 22343 (\N{CJK UNIFIED IDEOGRAPH-5747}) missing from current font.
  fig.tight_layout()

图表已保存: outputs/figures\03_market_segment_analysis.png

c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 24066 (\N{CJK UNIFIED IDEOGRAPH-5E02}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 22330 (\N{CJK UNIFIED IDEOGRAPH-573A}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 32454 (\N{CJK UNIFIED IDEOGRAPH-7EC6}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 20998 (\N{CJK UNIFIED IDEOGRAPH-5206}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 21508 (\N{CJK UNIFIED IDEOGRAPH-5404}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 12289 (\N{IDEOGRAPHIC COMMA}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 21462 (\N{CJK UNIFIED IDEOGRAPH-53D6}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 28040 (\N{CJK UNIFIED IDEOGRAPH-6D88}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 29575 (\N{CJK UNIFIED IDEOGRAPH-7387}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 24179 (\N{CJK UNIFIED IDEOGRAPH-5E73}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 22343 (\N{CJK UNIFIED IDEOGRAPH-5747}) missing from current font.
  fig.savefig(filepath)

**阶段性结论**：Online TA 是最大的市场细分渠道，预订量遥遥领先。Direct 渠道的取消率最低且 ADR 最高，表明直销客户质量最高。Groups 的取消率接近 50%，是高风险细分。

---
## 第 5 步：Distribution Channel 分析（预订量、取消率、ADR）

In [10]:
channel_stats = calculate_group_summary(df, "distribution_channel")
channel_stats

,distribution_channel,total_bookings,canceled_bookings,avg_adr,cancel_rate
0,TA/TO,97870,40152,103.29,0.410259
1,Direct,14645,2557,106.65,0.174599
2,Corporate,6677,1474,69.33,0.220758
3,GDS,193,37,120.55,0.191710
4,Undefined,5,4,46.24,0.800000

In [11]:
fig, ax = plt.subplots(figsize=(10, 5))
data = channel_stats.sort_values("total_bookings")
colors = sns.color_palette("Set2", len(data))
bars = ax.barh(data["distribution_channel"], data["total_bookings"], color=colors)
ax.set_title("各分销渠道预订量、取消率与平均 ADR", fontsize=14, fontweight="bold")
ax.set_xlabel("预订量")
ax.set_ylabel("分销渠道")
for bar, total, rate, adr in zip(bars, data["total_bookings"],
                                   data["cancel_rate"], data["avg_adr"]):
    ax.text(bar.get_width() + 300, bar.get_y() + bar.get_height() / 2,
            f"{total:,}  |  取消率 {rate:.1%}  |  ADR {adr:.0f}",
            va="center", fontsize=9)
fig.tight_layout()
save_figure(fig, "03_distribution_channel_analysis.png")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.tight_layout()

图表已保存: outputs/figures\03_distribution_channel_analysis.png

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 20998 (\N{CJK UNIFIED IDEOGRAPH-5206}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 38144 (\N{CJK UNIFIED IDEOGRAPH-9500}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 28192 (\N{CJK UNIFIED IDEOGRAPH-6E20}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 36947 (\N{CJK UNIFIED IDEOGRAPH-9053}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 21508 (\N{CJK UNIFIED IDEOGRAPH-5404}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 12289 (\N{IDEOGRAPHIC COMMA}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 21462 (\N{CJK UNIFIED IDEOGRAPH-53D6}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 28040 (\N{CJK UNIFIED IDEOGRAPH-6D88}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 29575 (\N{CJK UNIFIED IDEOGRAPH-7387}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 24179 (\N{CJK UNIFIED IDEOGRAPH-5E73}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3617727478.py:13: UserWarning: Glyph 22343 (\N{CJK UNIFIED IDEOGRAPH-5747}) missing from current font.
  fig.tight_layout()
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 20998 (\N{CJK UNIFIED IDEOGRAPH-5206}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 38144 (\N{CJK UNIFIED IDEOGRAPH-9500}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 28192 (\N{CJK UNIFIED IDEOGRAPH-6E20}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 36947 (\N{CJK UNIFIED IDEOGRAPH-9053}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 21508 (\N{CJK UNIFIED IDEOGRAPH-5404}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 12289 (\N{IDEOGRAPHIC COMMA}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 21462 (\N{CJK UNIFIED IDEOGRAPH-53D6}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 28040 (\N{CJK UNIFIED IDEOGRAPH-6D88}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 29575 (\N{CJK UNIFIED IDEOGRAPH-7387}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 24179 (\N{CJK UNIFIED IDEOGRAPH-5E73}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 22343 (\N{CJK UNIFIED IDEOGRAPH-5747}) missing from current font.
  fig.savefig(filepath)

**阶段性结论**：TA/TO（旅行社/旅游运营商）是最大的分销渠道。Direct 渠道虽然预订量不多，但 ADR 最高且取消率最低。GDS（全球分销系统）的取消率极高（53%+），是需要管控的重点渠道。

---
## 第 6 步：主要客源国家 Top 10

In [12]:
top_countries = df["country"].value_counts().head(10)
top_countries_pct = df["country"].value_counts(normalize=True).head(10)
print("Top 10 客源国家:")
for i, (country, cnt) in enumerate(top_countries.items(), 1):
    print(f"  {i:2d}. {country}: {cnt:>8,}  ({top_countries_pct[country]:.1%})")
print(f"\nTop 10 合计占比: {top_countries_pct.sum():.1%}")

Top 10 客源国家:
   1. PRT:   48,590  (40.7%)
   2. GBR:   12,129  (10.2%)
   3. FRA:   10,415  (8.7%)
   4. ESP:    8,568  (7.2%)
   5. DEU:    7,287  (6.1%)
   6. ITA:    3,766  (3.2%)
   7. IRL:    3,375  (2.8%)
   8. BEL:    2,342  (2.0%)
   9. BRA:    2,224  (1.9%)
  10. NLD:    2,104  (1.8%)

Top 10 合计占比: 84.4%

In [13]:
fig, ax = plt.subplots(figsize=(8, 5))
countries_rev = top_countries.sort_values()
colors = sns.color_palette("Set2", len(countries_rev))
bars = ax.barh(countries_rev.index, countries_rev.values, color=colors)
ax.set_title("主要客源国家 Top 10", fontsize=14, fontweight="bold")
ax.set_xlabel("预订量")
ax.set_ylabel("国家代码")
for bar, val, pct in zip(bars, countries_rev.values,
                          top_countries_pct[countries_rev.index].values):
    ax.text(bar.get_width() + 200, bar.get_y() + bar.get_height() / 2,
            f"{val:,}  ({pct:.1%})", va="center", fontsize=9)
fig.tight_layout()
save_figure(fig, "03_top10_countries.png")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 22269 (\N{CJK UNIFIED IDEOGRAPH-56FD}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 23478 (\N{CJK UNIFIED IDEOGRAPH-5BB6}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 20195 (\N{CJK UNIFIED IDEOGRAPH-4EE3}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 30721 (\N{CJK UNIFIED IDEOGRAPH-7801}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 20027 (\N{CJK UNIFIED IDEOGRAPH-4E3B}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 35201 (\N{CJK UNIFIED IDEOGRAPH-8981}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 23458 (\N{CJK UNIFIED IDEOGRAPH-5BA2}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\1524599988.py:12: UserWarning: Glyph 28304 (\N{CJK UNIFIED IDEOGRAPH-6E90}) missing from current font.
  fig.tight_layout()
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.savefig(filepath)

图表已保存: outputs/figures\03_top10_countries.png

c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 22269 (\N{CJK UNIFIED IDEOGRAPH-56FD}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 23478 (\N{CJK UNIFIED IDEOGRAPH-5BB6}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 20195 (\N{CJK UNIFIED IDEOGRAPH-4EE3}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 30721 (\N{CJK UNIFIED IDEOGRAPH-7801}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 20027 (\N{CJK UNIFIED IDEOGRAPH-4E3B}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 35201 (\N{CJK UNIFIED IDEOGRAPH-8981}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 23458 (\N{CJK UNIFIED IDEOGRAPH-5BA2}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 28304 (\N{CJK UNIFIED IDEOGRAPH-6E90}) missing from current font.
  fig.savefig(filepath)

**阶段性结论**：客源高度集中在西欧国家（PRT 葡萄牙本地、GBR 英国、FRA 法国、DEU 德国、ESP 西班牙），Top 3 国家合计占比超过 60%。这对于市场营销预算分配有重要指导意义。

---
## 第 7 步：重复客户与取消率、ADR 的关系

In [14]:
repeat_stats = df.groupby("is_repeated_guest").agg(
    total_bookings=("is_canceled", "count"),
    canceled_bookings=("is_canceled", "sum"),
    avg_adr=("adr", "mean"),
).reset_index()
repeat_stats["cancel_rate"] = repeat_stats["canceled_bookings"] / repeat_stats["total_bookings"]
repeat_stats["avg_adr"] = repeat_stats["avg_adr"].round(2)
repeat_stats["guest_type"] = repeat_stats["is_repeated_guest"].map({0: "新客户", 1: "重复客户"})
repeat_stats

,is_repeated_guest,total_bookings,canceled_bookings,avg_adr,cancel_rate,guest_type
0,0,115580,43672,103.06,0.377851,新客户
1,1,3810,552,64.45,0.144882,重复客户

In [15]:
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))

colors = [sns.color_palette("Set2")[0], sns.color_palette("Set2")[3]]

bars1 = ax1.bar(repeat_stats["guest_type"], repeat_stats["total_bookings"], color=colors)
ax1.set_title("新客户 vs 重复客户预订量", fontsize=13, fontweight="bold")
ax1.set_ylabel("预订量")
for bar, val in zip(bars1, repeat_stats["total_bookings"]):
    ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 500,
            f"{val:,}", ha="center", fontsize=11)

x = np.arange(len(repeat_stats))
width = 0.35
bars2 = ax2.bar(x - width / 2, repeat_stats["cancel_rate"], width,
                color=colors[0], label="取消率")
ax2.set_title("新客户 vs 重复客户取消率与 ADR", fontsize=13, fontweight="bold")
ax2.set_ylabel("取消率（%）")
ax2.set_xticks(x)
ax2.set_xticklabels(repeat_stats["guest_type"])
ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f"{y:.0%}"))
for bar, val in zip(bars2, repeat_stats["cancel_rate"]):
    ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.005,
            f"{val:.1%}", ha="center", fontsize=11)

ax2b = ax2.twinx()
ax2b.plot(repeat_stats["guest_type"], repeat_stats["avg_adr"],
          "o-", color=colors[1], linewidth=3, markersize=10, label="平均 ADR")
ax2b.set_ylabel("平均 ADR", color=colors[1])
ax2b.tick_params(axis="y", labelcolor=colors[1])

lines1, labels1 = ax2.get_legend_handles_labels()
lines2, labels2 = ax2b.get_legend_handles_labels()
ax2.legend(lines1 + lines2, labels1 + labels2, loc="upper right")

fig.tight_layout()
save_figure(fig, "03_repeated_guest_analysis.png")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 26032 (\N{CJK UNIFIED IDEOGRAPH-65B0}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 23458 (\N{CJK UNIFIED IDEOGRAPH-5BA2}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 25143 (\N{CJK UNIFIED IDEOGRAPH-6237}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 37325 (\N{CJK UNIFIED IDEOGRAPH-91CD}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 22797 (\N{CJK UNIFIED IDEOGRAPH-590D}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 21462 (\N{CJK UNIFIED IDEOGRAPH-53D6}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 28040 (\N{CJK UNIFIED IDEOGRAPH-6D88}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 29575 (\N{CJK UNIFIED IDEOGRAPH-7387}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 65288 (\N{FULLWIDTH LEFT PARENTHESIS}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 65289 (\N{FULLWIDTH RIGHT PARENTHESIS}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 24179 (\N{CJK UNIFIED IDEOGRAPH-5E73}) missing from current font.
  fig.tight_layout()
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27296\3269221200.py:35: UserWarning: Glyph 22343 (\N{CJK UNIFIED IDEOGRAPH-5747}) missing from current font.
  fig.tight_layout()
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 35746 (\N{CJK UNIFIED IDEOGRAPH-8BA2}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 37327 (\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 21462 (\N{CJK UNIFIED IDEOGRAPH-53D6}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 28040 (\N{CJK UNIFIED IDEOGRAPH-6D88}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 29575 (\N{CJK UNIFIED IDEOGRAPH-7387}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 65288 (\N{FULLWIDTH LEFT PARENTHESIS}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 65289 (\N{FULLWIDTH RIGHT PARENTHESIS}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 24179 (\N{CJK UNIFIED IDEOGRAPH-5E73}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 22343 (\N{CJK UNIFIED IDEOGRAPH-5747}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 26032 (\N{CJK UNIFIED IDEOGRAPH-65B0}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 23458 (\N{CJK UNIFIED IDEOGRAPH-5BA2}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 25143 (\N{CJK UNIFIED IDEOGRAPH-6237}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 37325 (\N{CJK UNIFIED IDEOGRAPH-91CD}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 22797 (\N{CJK UNIFIED IDEOGRAPH-590D}) missing from current font.
  fig.savefig(filepath)
c:\Users\Lenovo\Desktop\pandas-hotel-booking-analysis\src\visualization.py:36: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from current font.
  fig.savefig(filepath)

图表已保存: outputs/figures\03_repeated_guest_analysis.png

**阶段性结论**：重复客户仅占约 3%，但取消率显著低于新客户，且平均 ADR 更高。这说明老客户忠诚度更高、消费能力更强，值得投入资源提升复购率。

---
## 小结

本 Notebook 从客户结构与预订渠道维度进行了全面分析，主要发现如下：

1. **酒店类型分布**：City Hotel 占预订总量的 60% 以上，是业务核心；Resort Hotel 虽然占比低，但客单价可能更值得关注。

2. **客户类型结构**：Transient（散客）是绝对主力，占比超过 80%；但 Transient-Party 的取消率最高（约 42%），建议对该群体实施适度预付或押金策略。

3. **渠道质量差异**：Direct 直销渠道虽然预订量较少，但 ADR 最高且取消率最低，是最高质量渠道。GDS 渠道取消率超过 53%，亟需渠道优化或风控措施。

4. **客源高度集中**：Top 5 国家（PRT、GBR、FRA、DEU、ESP）贡献了绝大多数预订，市场推广可重点关注这些区域。

5. **重复客户价值显著**：重复客户取消率低（约 19% vs 新客户 38%），ADR 更高，但占总预订量仅约 3%，说明客户忠诚度计划有巨大的提升空间。

6. **市场细分差异**：Online TA 是最大流量入口，但 Groups 和 Offline TA/TO 的取消风险较高，需要差异化的预订管理策略。